#!/usr/bin/env bash
# Dotfile installer
# Usage: install <files> or install all or install list

available="bashrc nanorc neofetch gtk herbstluftwm polybar xfce4-terminal rofi backgrounds jgmenu picom bin"
[[ -z "$*" ]] && echo "Usage: install <names> or install all or install list" && exit 1
[[ "$*" == *"list"* ]] && echo "$available"

if [[ "$*" == *"all"* ]]; then tocopy="$available"; else tocopy="$*"; fi

ppwd="$PWD"
cd $(dirname "$0")

[[ ! -e ~/.config ]] && mkdir ~/.config

for f in $tocopy; do
	case $f in
		        bashrc) cp .config/bashrc ~/.bashrc;;
		        nanorc) cp .config/nanorc ~/.nanorc;;
		      neofetch) cp -r .config/neofetch ~/.config;;
		           gtk) cp -r .config/gtk-3.0 ~/.config; cp .config/gtkrc-2.0 ~/.gtkrc-2.0; [[ ! -e /usr/share/fonts ]] && sudo mkdir -p /usr/share/fonts; sudo cp -r .fonts/* /usr/share/fonts; sudo cp -r .themes/* /usr/share/themes;;
		  herbstluftwm) cp -r .config/herbstluftwm ~/.config;;
		       polybar) cp -r .config/polybar ~/.config;;
		xfce4-terminal) [[ ! -e ~/.config/xfce4 ]] && mkdir ~/.config/xfce4; cp -r .config/xfce4/terminal ~/.config/xfce4/;;
		          rofi) cp -r .config/rofi ~/.config;;
		   backgrounds) cp -r .backgrounds ~/;;
		        jgmenu) cp -r .config/jgmenu ~/config;;
			     picom) cp -r .config/picom ~/config; [[ -e ~/.config/compton.conf ]] && mv ~/.config/compton.conf{,.old};;
			       bin) [[ ! -e ~/.bin ]] && mkdir ~/.bin; cp -r .bin/* ~/.bin/;;
	esac
done

cd "$ppwd"
