#!/usr/bin/env bash
# Dotfile installer
# Usage: install <files> or install all or install list

available="bashrc nanorc neofetch gtk herbstluftwm polybar xfce4-terminal"
[[ -z "$*" ]] && echo "Usage: install <names> or install all or install list" && exit 1
[[ "$*" == *"list"* ]] && echo "$available"

if [[ "$*" == *"all"* ]]; then tocopy="$available"; else tocopy="$*"; fi

ppwd="$PWD"
cd $(dirname "$0")

[[ ! -e ~/.config ]] && mkdir ~/.config

for f in $tocopy; do
	case $f in
		        bashrc) cp .config/bashrc ~/.bashrc;;
		        nanorc) cp .config/nanorc ~/.nanorc;;
		      neofetch) cp -r .config/neofetch ~/.config;;
		           gtk) cp -r .config/gtk-3.0 ~/.config; cp .config/gtkrc-2.0 ~/.gtkrc-2.0; sudo cp .fonts/* /usr/share/fonts/TTF; sudo cp -r .themes/* /usr/share/themes;;
		  herbstluftwm) cp -r .config/herbstluftwm ~/.config;;
		       polybar) cp -r .config/polybar ~/.config;;
		xfce4-terminal) [[ ! -e ~/.config/xfce4 ]] && mkdir ~/.config/xfce4; cp -r .config/xfce4/terminal ~/.config/xfce4/;;
		          rofi) [[ ! -e ~/.config/rofi ]] && mkdir ~/.config/rofi; cp -r .config/rofi ~/.config;;
	esac
done

cd "$ppwd"
